import { useEffect, useState } from 'react'
import { ArrowRight, Building2, CheckSquare, FolderKanban, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { currentUser } from '../auth/auth'
import { getProjects, getTasks } from '../data/store'
import type { Project, Task } from '../types'
import { Badge, Loading, PageHeader } from '../components/UI'

export function Dashboard() {
  const navigate = useNavigate(); const user = currentUser(); const [projects, setProjects] = useState<Project[] | null>(null); const [tasks, setTasks] = useState<Task[] | null>(null)
  useEffect(() => { Promise.all([getProjects(), getTasks()]).then(([nextProjects, nextTasks]) => { setProjects(nextProjects); setTasks(nextTasks) }) }, [])
  if (!projects || !tasks) return <main className="p-8"><Loading /></main>
  const visibleProjects = projects.filter((project) => user?.role === 'SUPER_ADMIN' || project.organizationId === user?.organizationId); const visibleTasks = tasks.filter((task) => visibleProjects.some((project) => project.id === task.projectId)); const metrics = [{ label: 'Organizations', value: user?.role === 'SUPER_ADMIN' ? '3' : '1', icon: Building2 }, { label: 'Active projects', value: `${visibleProjects.filter((project) => project.status === 'Active').length}`, icon: FolderKanban }, { label: 'Open tasks', value: `${visibleTasks.filter((task) => task.status !== 'Done').length}`, icon: CheckSquare }, { label: 'Team members', value: '5', icon: Users }]
  return <main className="p-8"><PageHeader title={`Good morning, ${user?.name.split(' ')[0] || 'there'}`} subtitle="Here is what needs your attention today." /><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => { const Icon = metric.icon; return <button key={metric.label} onClick={() => metric.label.includes('task') ? navigate('/tasks') : metric.label.includes('project') ? navigate('/projects') : navigate('/organizations')} className="rounded-panel border border-line bg-surface p-5 text-left shadow-sm transition hover:-translate-y-0.5"><Icon size={19} className="text-primary" /><p className="mt-5 text-3xl font-bold text-ink">{metric.value}</p><p className="mt-1 text-sm text-secondary">{metric.label}</p></button> })}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-panel border border-line bg-surface p-6"><div className="flex justify-between"><h2 className="font-bold text-ink">Recent projects</h2><button onClick={() => navigate('/projects')} className="text-sm font-semibold text-primary">View all</button></div><div className="mt-5 space-y-3">{visibleProjects.slice(0, 3).map((project) => <button key={project.id} onClick={() => navigate(`/projects/${project.id}`)} className="flex w-full items-center justify-between rounded-xl bg-muted p-4 text-left hover:bg-indigo-50"><div><p className="font-semibold text-ink">{project.name}</p><p className="mt-1 text-xs text-secondary">{project.description}</p></div><Badge>{project.status}</Badge></button>)}</div></section><section className="rounded-panel border border-line bg-surface p-6"><h2 className="font-bold text-ink">Your next tasks</h2><div className="mt-5 space-y-3">{visibleTasks.slice(0, 3).map((task) => <button key={task.id} onClick={() => navigate(`/tasks/${task.id}`)} className="flex w-full items-center justify-between border-b border-line py-3 text-left"><div><p className="font-semibold text-ink">{task.title}</p><p className="mt-1 text-xs text-secondary">{task.status}</p></div><ArrowRight size={17} className="text-secondary" /></button>)}</div></section></div></main>
}
