import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { login } from '../auth/auth'
import { email, password } from '../validation'

export function Login() {
  const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [attempted, setAttempted] = useState(false); const [message, setMessage] = useState('')
  const valid = !email(form.email) && !password(form.password)
  const submit = async (event: FormEvent) => { event.preventDefault(); setAttempted(true); if (!valid) return; if (await login(form.email, form.password)) navigate('/dashboard'); else setMessage('Invalid email or password.') }
  return <main className="grid min-h-screen bg-canvas lg:grid-cols-2"><section className="hidden bg-ink p-16 text-white lg:block"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary text-xl font-bold">O</span><h1 className="mt-32 max-w-md text-5xl font-bold leading-tight">Bring every team into focus.</h1><p className="mt-6 max-w-md text-lg leading-8 text-slate-400">A calm shared space for organizations, projects, and everyday work.</p></section><section className="grid place-items-center p-6"><form className="w-full max-w-md rounded-panel border border-line bg-surface p-8 shadow-sm" onSubmit={submit}><h2 className="text-2xl font-bold text-ink">Welcome back</h2><p className="mt-2 text-sm text-secondary">Sign in to your osa workspace.</p>{message && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-danger">{message}</p>}<label className="mt-7 block text-sm font-semibold text-ink">Email<input value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="mt-2 w-full rounded-xl border border-line px-3 py-2.5 outline-none focus:ring-2 focus:ring-primary" placeholder="you@company.com" /></label>{attempted && email(form.email) && <p className="mt-1 text-xs text-danger">{email(form.email)}</p>}<label className="mt-5 block text-sm font-semibold text-ink">Password<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="mt-2 w-full rounded-xl border border-line px-3 py-2.5 outline-none focus:ring-2 focus:ring-primary" /></label><p className="mt-1 text-xs text-secondary">At least 6 characters.</p>{attempted && password(form.password) && <p className="mt-1 text-xs text-danger">{password(form.password)}</p>}<Link className="mt-3 inline-block text-sm font-semibold text-primary" to="/forgot-password">Forgot password?</Link><button disabled={!valid} className="mt-7 w-full rounded-xl bg-primary py-3 text-sm font-semibold text-white disabled:opacity-50">Sign in</button><p className="mt-5 text-center text-xs text-secondary">Demo: admin@osa.demo / password123</p></form></section></main>
}
