import React from 'react'
import { RouteComponentProps, withRouter } from 'react-router-dom'
import { login } from '../auth/auth'
import { email, password } from '../validation/fields'
interface State { email: string; password: string; submitted: boolean; error: string; loading: boolean }
class LoginView extends React.Component<RouteComponentProps, State> {
  state: State = { email: 'admin@example.com', password: 'password123', submitted: false, error: '', loading: false }
  render() { const valid = !email(this.state.email) && !password(this.state.password); return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-5"><form onSubmit={async (event) => { event.preventDefault(); this.setState({ submitted: true }); if (!valid) return; this.setState({ loading: true, error: '' }); if (await login(this.state.email, this.state.password)) this.props.history.push('/dashboard'); else this.setState({ loading: false, error: 'Invalid email or password' }) }} className="w-full max-w-md rounded-card bg-surface p-8 shadow-2xl"><p className="mb-2 text-sm font-semibold text-primary">AXIS RBAC</p><h1 className="text-3xl font-bold text-ink">Welcome back</h1><p className="mt-2 text-sm text-muted">Sign in to access your organization workspace.</p>{this.state.error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-danger">{this.state.error}</p>}<label className="mt-6 block text-sm font-medium">Email<input value={this.state.email} onChange={(event) => this.setState({ email: event.target.value })} className="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label>{this.state.submitted && email(this.state.email) && <p className="mt-1 text-xs text-danger">{email(this.state.email)}</p>}<label className="mt-4 block text-sm font-medium">Password<input type="password" value={this.state.password} onChange={(event) => this.setState({ password: event.target.value })} className="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label><p className="mt-1 text-xs text-muted">At least 6 characters</p><button type="button" onClick={() => this.props.history.push('/forgot-password')} className="mt-2 text-sm text-primary">Forgot password?</button><button disabled={!valid || this.state.loading} className="mt-6 w-full rounded-lg bg-primary py-3 font-semibold text-white hover:bg-primary-dark">{this.state.loading ? 'Signing in…' : 'Sign in'}</button><p className="mt-5 text-xs text-muted">Demo: admin@example.com / password123</p></form></main> }
}
export const Login = withRouter(LoginView)
