import React from 'react'
import { RouteComponentProps, withRouter } from 'react-router-dom'
import { createOrganization, createProject, createTask, getOrganizations, getProjects, getTasks } from '../data/store'
interface State { items: any[]; loading: boolean; search: string; title: string; description: string; submitted: boolean; success: string }
class ResourceListView extends React.Component<RouteComponentProps<{ kind: string }>, State> {
  state: State = { items: [], loading: true, search: '', title: '', description: '', submitted: false, success: '' }
  componentDidMount() { this.load() }
  load() { const kind = this.props.match.params.kind; const loader = kind === 'organizations' ? getOrganizations : kind === 'projects' ? getProjects : getTasks; loader().then((items) => this.setState({ items, loading: false })) }
  render() { const kind = this.props.match.params.kind; const label = kind === 'organizations' ? 'Organizations' : kind === 'projects' ? 'Projects' : 'Tasks'; const filtered = this.state.items.filter((item) => (item.name || item.title).toLowerCase().indexOf(this.state.search.toLowerCase()) >= 0); return <div><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">{label}</h1><p className="mt-2 text-muted">Manage the work your role is authorized to access.</p></div><button onClick={() => this.props.history.push(`/${kind}/new`)} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Create {label.slice(0, -1)}</button></div><input value={this.state.search} onChange={(event) => this.setState({ search: event.target.value })} placeholder={`Search ${label.toLowerCase()}`} className="mt-6 w-full max-w-sm rounded-lg border border-border bg-surface px-3 py-2" /><div className="mt-5 overflow-hidden rounded-card border border-border bg-surface">{this.state.loading ? <div className="space-y-3 p-6"><div className="h-5 w-2/3 animate-pulse rounded bg-slate-100" /><div className="h-5 w-full animate-pulse rounded bg-slate-100" /></div> : filtered.length ? <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-muted"><tr><th className="p-4">Name</th><th className="p-4">Status</th><th className="p-4">Created</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} onClick={() => this.props.history.push(`/${kind}/${item.id}`)} className="cursor-pointer border-t border-border hover:bg-accent"><td className="p-4 font-semibold">{item.name || item.title}</td><td className="p-4">{item.status || item.plan || 'Active'}</td><td className="p-4 text-muted">{item.createdAt}</td></tr>)}</tbody></table> : <p className="p-8 text-center text-muted">No {label.toLowerCase()} yet — create one.</p>}</div></div> }
}
class ResourceCreateView extends React.Component<RouteComponentProps<{ kind: string }>, State> { state: State = { items: [], loading: false, search: '', title: '', description: '', submitted: false, success: '' }; render() { const kind = this.props.match.params.kind; const label = kind === 'organizations' ? 'organization' : kind === 'projects' ? 'project' : 'task'; const valid = this.state.title.trim().length > 2; return <div className="max-w-2xl"><button onClick={() => this.props.history.goBack()} className="text-sm font-medium text-primary">← Back</button><h1 className="mt-4 text-3xl font-bold">Create {label}</h1><form onSubmit={async (event) => { event.preventDefault(); this.setState({ submitted: true }); if (!valid) return; let item: any; if (kind === 'organizations') item = await createOrganization({ name: this.state.title, plan: 'Starter', memberCount: 0, projectCount: 0 }); else if (kind === 'projects') item = await createProject({ name: this.state.title, description: this.state.description, organizationId: 'o1', status: 'Planning', memberIds: ['u2'] }); else item = await createTask({ title: this.state.title, description: this.state.description, projectId: 'p1', assigneeId: 'u2', status: 'To do', dueDate: '2024-12-31' }); this.setState({ success: 'Saved successfully' }); this.props.history.push(`/${kind}/${item.id}`) }} className="mt-6 rounded-card border border-border bg-surface p-6"><label className="block text-sm font-medium">Name / title<input value={this.state.title} onChange={(event) => this.setState({ title: event.target.value })} className="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label>{this.state.submitted && !valid && <p className="mt-1 text-xs text-danger">Enter at least 3 characters.</p>}<label className="mt-4 block text-sm font-medium">Description<textarea value={this.state.description} onChange={(event) => this.setState({ description: event.target.value })} className="mt-2 min-h-28 w-full rounded-lg border border-border px-3 py-3" /></label><div className="mt-6 flex gap-3"><button type="button" onClick={() => this.props.history.goBack()} className="rounded-lg border border-border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={!valid} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Save {label}</button></div></form></div> } }
class ResourceDetailView extends React.Component<RouteComponentProps<{ kind: string; id: string }>, State> { state: State = { items: [], loading: true, search: '', title: '', description: '', submitted: false, success: '' }; componentDidMount() { const kind = this.props.match.params.kind; (kind === 'organizations' ? getOrganizations() : kind === 'projects' ? getProjects() : getTasks()).then((items) => this.setState({ items, loading: false })) } render() { const item = this.state.items.filter((entry) => entry.id === this.props.match.params.id)[0]; if (this.state.loading) return <div className="h-36 animate-pulse rounded-card bg-slate-200" />; if (!item) return <div className="rounded-card bg-surface p-6">This resource is unavailable.</div>; return <div><button onClick={() => this.props.history.goBack()} className="text-sm text-primary">← Back to list</button><section className="mt-5 rounded-card border border-border bg-surface p-7"><p className="text-sm font-semibold text-primary">{this.props.match.params.kind.slice(0, -1).toUpperCase()}</p><h1 className="mt-2 text-3xl font-bold">{item.name || item.title}</h1><p className="mt-4 max-w-2xl text-muted">{item.description || 'Organization workspace with managed members, permissions, and project activity.'}</p><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-lg bg-canvas p-4"><p className="text-xs text-muted">Status</p><p className="mt-1 font-semibold">{item.status || item.plan || 'Active'}</p></div><div className="rounded-lg bg-canvas p-4"><p className="text-xs text-muted">Created</p><p className="mt-1 font-semibold">{item.createdAt}</p></div></div></section></div> } }
export const ResourceList = withRouter(ResourceListView)
export const ResourceCreate = withRouter(ResourceCreateView)
export const ResourceDetail = withRouter(ResourceDetailView)
