import { useEffect, useState } from 'react'
import { Plus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { currentUser } from '../auth/auth'
import { Badge, Empty, Loading, PageHeader, primaryButton } from '../components/UI'
import { getProjects, getTasks } from '../data/store'
import type { Project, Task } from '../types'

export function Tasks() { const navigate = useNavigate(); const user = currentUser(); const [tasks, setTasks] = useState<Task[] | null>(null); const [projects, setProjects] = useState<Project[]>([]); useEffect(() => { Promise.all([getTasks(), getProjects()]).then(([nextTasks, nextProjects]) => { setTasks(nextTasks); setProjects(nextProjects) }) }, []); if (!tasks) return <main className="p-8"><Loading /></main>; const permitted = projects.filter((project) => user?.role === 'SUPER_ADMIN' || project.organizationId === user?.organizationId).map((project) => project.id); const filtered = tasks.filter((task) => permitted.includes(task.projectId)); const canCreate = user?.role !== 'VIEWER'; return <main className="p-8"><PageHeader title="Tasks" subtitle="Track the work that keeps projects moving." action={canCreate ? <button onClick={() => navigate('/tasks/new')} className={primaryButton}><Plus size={16} className="mr-2 inline" />New task</button> : undefined} />{filtered.length ? <div className="overflow-hidden rounded-panel border border-line bg-surface"><table className="w-full text-left text-sm"><thead className="bg-muted text-xs uppercase text-secondary"><tr><th className="p-4">Task</th><th className="p-4">Project</th><th className="p-4">Status</th></tr></thead><tbody>{filtered.map((task) => <tr key={task.id} onClick={() => navigate(`/tasks/${task.id}`)} className="cursor-pointer border-t border-line hover:bg-indigo-50"><td className="p-4"><p className="font-semibold text-ink">{task.title}</p><p className="mt-1 text-xs text-secondary">{task.description}</p></td><td className="p-4 text-secondary">{projects.find((project) => project.id === task.projectId)?.name}</td><td className="p-4"><Badge>{task.status}</Badge></td></tr>)}</tbody></table></div> : <Empty>No tasks yet — create one to get started.</Empty>}</main> }
